// Code generated by mockery v1.0.0
package cqrs

import mock "github.com/stretchr/testify/mock"

// MockAggregate is an autogenerated mock type for the Aggregate type
type MockAggregate struct {
	mock.Mock
}

// AggregateName provides a mock function with given fields:
func (_m *MockAggregate) AggregateName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Apply provides a mock function with given fields: _a0
func (_m *MockAggregate) Apply(_a0 Event) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(Event) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleCommand provides a mock function with given fields: _a0
func (_m *MockAggregate) HandleCommand(_a0 Command) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(Command) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
