// Code generated by mockery v1.0.0
package cqrs

import mock "github.com/stretchr/testify/mock"
import time "time"
import uuid "github.com/satori/go.uuid"

// MockEventFactory is an autogenerated mock type for the EventFactory type
type MockEventFactory struct {
	mock.Mock
}

// MakeEvent provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockEventFactory) MakeEvent(_a0 string, _a1 uuid.UUID, _a2 int, _a3 time.Time) Event {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 Event
	if rf, ok := ret.Get(0).(func(string, uuid.UUID, int, time.Time) Event); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Event)
		}
	}

	return r0
}
